/// Flutter icons Ecommerce_bank_pay
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ecommerce_bank_pay
///      fonts:
///       - asset: fonts/Ecommerce_bank_pay.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Ecommerce_bank_pay {
  Ecommerce_bank_pay._();

  static const _kFontFam = 'Ecommerce_bank_pay';
  static const _kFontPkg = null;

  static const IconData arrow_blue = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boleto = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData companie = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_pagamento = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mpos = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credito_online = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
